### ISSUE TITLE
Survivor Images Blocking Some Perks

### ISSUE THREAD

**Issue by Irraticate** [MrTipson/otz-builds#1]
When going onto [the survivor build page](https://mrtipson.github.io/otz-builds/) the images of the survivors, especially Claudette, block some perks from being seen. This also stops them from being hovered over and clicking them.

![image](https://user-images.githubusercontent.com/42052753/204109104-15f67f59-0a86-4be5-b79c-f431dedb0cc4.png)

**Comment by MrTipson** [comment]
Can you try hard reloading (Ctrl+F5 or right click on refresh button)? If that doesn't work, what browser are you using?

**Comment by Irraticate** [comment]
Hard reloading doesn't result in any changes. I am using the current version of Firefox.

**Comment by MrTipson** [comment]
Thanks, will look into it.

**Comment by MrTipson** [comment]
Should work now, will try to be more mindful of browser support in the future.
