### ISSUE TITLE
Suggestion for a new survivor build that utilizies Lightweight

### ISSUE THREAD

**Issue by affectioned** [MrTipson/otz-builds#4]
I personally see and find the perk [Lightweight](https://deadbydaylight.fandom.com/wiki/Lightweight) very useful and starting to get more common. I was wondering if you would be down to make Lightweight centered build. I feel like it's one of the perks that could help beginners a lot. Let me know your opinion.

**Comment by MrTipson** [comment]
Hi,
the issues section here on Github is intended as a place to submit bug reports (such as issues with browser compatibility, accessibility and other things that negatively affect the website's functionality). 

Everything regarding the perk selection is done by Otz, so you should try asking him (in twitch chat for example). Every now and then he also tests and updates builds live on stream, which is a great opportunity to share your ideas with him and the community.
